### ISSUE TITLE
Creating a log entry after consumption fails with django.contrib.auth.models.DoesNotExist: User matching query does not exist.

### ISSUE THREAD

**Issue by ddddavidmartin** [danielquinn/paperless#349] opened 2018-04-30 07:17 UTC
Hi all,

since yesterday I believe I am seeing this error where the consumer crashes after consuming a document whilst trying to add an entry to the log. Detailed log file:

```
Consuming /home/littlebig/paperless_consumption_dir/MART-0601-DEPN-00000001_20180430-1510.pdf
Skipping OCR, using Text from PDF
Detected document date 2018-04-29T00:00:00+10:00 based on string 29/04/2018
Completed
Document 20180429000000: MART-0601-DEPN-00000001_20180430-1510 consumption finished
Traceback (most recent call last):
  File "src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/littlebig/Dev/paperless/src/documents/management/commands/document_consumer.py", line 85, in handle
    self.loop(mail_delta=mail_delta)
  File "/home/littlebig/Dev/paperless/src/documents/management/commands/document_consumer.py", line 105, in loop
    self.file_consumer.run()
  File "/home/littlebig/Dev/paperless/src/documents/consumer.py", line 151, in run
    logging_group=self.logging_group
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/littlebig/Dev/paperless/src/documents/signals/handlers.py", line 105, in set_log_entry
    user = User.objects.get(username="consumer")
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/littlebig/.local/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
```

I haven't changed anything in my setup other than pulling the latest version. I'm running a bare instance, so no docker or anything. Any ideas what is going on? Thanks!

**Comment by ddddavidmartin** [comment] 2018-04-30 07:25
Hmmm, now the consumer does not crash but I am still not seeing an entry for the newly consumed document under `Recent actions`. Does this work as expected for everyone else?

**Comment by danielquinn** [comment] 2018-04-30 09:18
That migration creates a `consumer` user which is now credited with all document creation in each `LogEntry`.  If you're not seeing those log entries, maybe there's some permissions thing I wasn't aware of?  Here's some relevant questions:

* The user you're currently accessing the admin as, is that a superuser?  Ie. Was it created with `createsuperuser` as per the installation docs?
* If you log into the Django shell with `./manage.py shell_plus`, what's the output of `LogEntry.objects.all()`?
    * What about `LogEntry.objects.order_by("-pk")` (descending order)
    * Is the output what you'd expect?  You can always try interrogating each LogEntry object.

**Comment by ddddavidmartin** [comment] 2018-05-01 06:40
Thanks for the pointers @danielquinn! This is a bit strange.

Yes, I am pretty sure I am using a superuser as I only have one user and followed the docs with the initial setup.

The interactive output:
```
>>> LogEntry.objects.order_by("-pk")
<QuerySet [2018-05-01 06:25:01.712473+00:00, 2018-04-30 07:21:55.710089+00:00, 2018-04-23 07:56:29.533807+00:00, 2018-04-19 08:01:11.957251+00:00, 2018-04-19 06:15:22.354656+00:00, 2018-04-19 06:14:27.943865+00:00, 2018-04-17 07:33:18.596025+00:00, 2018-04-17 07:32:41.410541+00:00, 2018-04-17 07:30:17.011010+00:00, 2018-04-17 07:28:06.046224+00:00, 2018-04-12 04:30:44.042251+00:00, 2018-04-12 04:19:43.001544+00:00, 2018-04-11 03:59:20.035584+00:00, 2018-04-11 03:57:26.784167+00:00, 2018-04-11 03:56:43.005672+00:00, 2018-04-11 01:13:29.610034+00:00, 2018-04-11 01:12:18.487823+00:00, 2018-04-10 12:07:43.596722+00:00, 2018-04-10 11:55:21.259324+00:00, 2018-04-10 11:46:54.152599+00:00, '...(remaining elements truncated)...']>
```

Or more specifically:
```
>>> s = LogEntry.objects.order_by("-pk")
>>> for i in range(20):
...     print("object: %s, message: %s" % (s[i], s[i].change_message))
...
object: Added "20180429000000: binarylane_invoice"., message:
object: Added "20140413000000: Petplan-EssentialNew-PDS-1214"., message:
object: Changed "20180402000000: USB C 2m Cable JB Hifi" - Changed title and content., message: [{"changed": {"fields": ["title", "content"]}}]
object: Added "20180402000000: BRW90CDB68D60F5_000768"., message:
```

So in the log the recent actions are present. I do not see them in the webserver though:

<img width="292" alt="screen shot 2018-05-01 at 4 38 45 pm" src="https://user-images.githubusercontent.com/710898/39463945-3cb09074-4d5e-11e8-85a9-d76d76ff2de1.png">

The third oldest entry is visible but not the ones after that. Any ideas?

**Comment by ddddavidmartin** [comment] 2018-05-01 06:44
Also, when I modify one of the new documents the modification shows up as an item under 'My actions'. It appears that just the entries for newly added documents are missing, but not changes on them themselves. 🤔

**Comment by danielquinn** [comment] 2018-05-20 15:31
Looking into this now, I see the problem, and I'm afraid the fix isn't going to be awesome.

The problem is that in [this pull request](https://github.com/danielquinn/paperless/pull/340/files) we introduced the `consumer` user which now takes responsibility for all consumption.  *However* by default, Django's admin only shows `LogEntry` objects in that sidebar *for the logged-in-user only*.

The fix was to override the admin further by adding a new `index.html` that just calls the templatetag for that sidebar without a user argument.  It's ugly, but it works, and it's just a template hack so I'm happy with it.

I'll close this, but if you guys notice something still broken about it, let me know by re-opening.

**Closed by danielquinn** 2018-05-20 15:31 UTC

**Comment by ddddavidmartin** [comment] 2018-05-20 23:39
I very much appreciate you taking the time to look into this one, @danielquinn! Ugly or not, it looks like it works fine again which is great.
