### ISSUE TITLE
DecompressionBombWarning

### ISSUE THREAD

**Issue by polo2ro** [danielquinn/paperless#118] opened 2016-04-27 16:28 UTC
Hi,
what do you thin about this error message?

i got paperless working with single pages jpg documents, i got this error when i merged 3 pages in the same PDF with `convert`. The result of this is no text in content.

```
avril 27 08:21:57 nas systemd[1]: Starting Paperless consumer...
avril 27 08:21:57 nas systemd[1]: Started Paperless consumer.
avril 27 08:22:03 nas python3[30035]: Starting document consumer at /var/share/paperless
avril 27 08:22:03 nas python3[30035]: Consuming /var/share/paperless/Scan - 2016-04-26-21-39-06.pdf
avril 27 08:22:03 nas python3[30035]: Generating greyscale image from /var/share/paperless/Scan - 2016-04-26-21-39-06.pdf
avril 27 09:04:23 nas python3[30035]: Processing sheet #1: /tmp/paperless/paperlessn1joq9ih/convert-0001.pnm -> /tmp/paperless/paperlessn1joq9ih/convert-0001.unpaper.pnm
avril 27 10:06:36 nas python3[30035]: Processing sheet #1: /tmp/paperless/paperlessn1joq9ih/convert-0002.pnm -> /tmp/paperless/paperlessn1joq9ih/convert-0002.unpaper.pnm
avril 27 10:25:46 nas python3[30035]: Processing sheet #1: /tmp/paperless/paperlessn1joq9ih/convert-0000.pnm -> /tmp/paperless/paperlessn1joq9ih/convert-0000.unpaper.pnm
avril 27 10:25:47 nas python3[30035]: Generating the thumbnail
avril 27 10:27:43 nas python3[30035]: OCRing the document
avril 27 10:27:44 nas python3[30035]: Parsing for eng
avril 27 10:27:45 nas python3[30035]: /usr/local/lib/python3.4/dist-packages/PIL/Image.py:2224: DecompressionBombWarning: Image size (147978893 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
avril 27 10:27:45 nas python3[30035]: DecompressionBombWarning)
avril 27 10:43:18 nas python3[30035]: Language detection error: No features in text.
avril 27 10:43:19 nas python3[30035]: Language detection failed!
avril 27 10:43:19 nas python3[30035]: As FORGIVING_OCR is enabled, we're going to make the best with what we have.
avril 27 10:43:20 nas python3[30035]: Parsing for eng
avril 27 10:43:21 nas python3[30035]: /usr/local/lib/python3.4/dist-packages/PIL/Image.py:2224: DecompressionBombWarning: Image size (147978893 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
avril 27 10:43:21 nas python3[30035]: DecompressionBombWarning)
avril 27 10:59:33 nas python3[30035]: Parsing for eng
avril 27 10:59:37 nas python3[30035]: /usr/local/lib/python3.4/dist-packages/PIL/Image.py:2224: DecompressionBombWarning: Image size (147978893 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
avril 27 10:59:37 nas python3[30035]: DecompressionBombWarning)
avril 27 11:15:35 nas python3[30035]: Completed
```
the generated pnm files from the pages seam to be very larges, is there a parameter to configure this?

**Comment by danielquinn** [comment] 2016-04-27 18:51
I dug up the `DecompressionBombWarning` and [it looks like it's nothing to worry about](https://pillow.readthedocs.org/en/3.2.x/reference/Image.html#functions).  The real problem appears to be that the image itself doesn't appear to have any text in it (according to Tesseract which is issuing the `No features in text` warning.

From the output above though, it looks like it's doing just what it's supposed to do: try to read the text in the image and if there's nothing to find, store `""`.  If you can provide a (scaled down!) copy of the image here and/or a link to the full PDF somewhere, I can take a look myself.

**Comment by polo2ro** [comment] 2016-04-27 18:55
Thanks for the quick reply, i will try t recreate the problem with another document because my pdf contain sensitive informations, then i will get back to you with more data, thanks again

**Comment by polo2ro** [comment] 2016-04-27 21:35
i think i understand the problem.
this is because i created my PDF without the density attribute, the used command in my script was `convert *.jpg scan.pdf`
then paperless does
`convert -density 300 -depth 8 -type grayscale scan.pdf tmp/paperless/convert.pnm`
the original jpg was 2380x3437px and the converted pnm is 10333x14321px

example file : https://1fichier.com/?za2185qwy3

adding the `-density 300` when creating the PDF fix the issue
removing the `-density 300` from the second command can also fix the issue

i can fix this on my side, maybe it is possible for paperless to check the document density before doing the pnm extraction?

**Comment by danielquinn** [comment] 2016-04-28 05:49
[I looked up `-density`](https://www.imagemagick.org/script/command-line-options.php#density) on the ImageMagick site and was reminded of why I'm using it in the first place: it's actually there to scale up images from the typical default (72dpi) to get a higher resolution and make OCRing them easier.

[Then it gets more complicated](http://www.dpiphoto.eu/dpi.htm).

The problem I have is that without the `-density 300`, converting PDFs to images basically generates unreadable garbage.

#### With  `-density 300`

![WIth -density 300](https://cloud.githubusercontent.com/assets/218205/14876450/dc2851da-0d0c-11e6-8c68-e89a0fac2703.png)

#### Without any `-density` argument

![Without any -density argument](https://cloud.githubusercontent.com/assets/218205/14876451/dc2b593e-0d0c-11e6-9b60-212bb8fdee20.png)

I think that the best option, given the above is to have the `-density` get added on your end and maybe document that in the troubleshooting section for anyone else who may come across this problem in the future.  What do you think?

**Comment by polo2ro** [comment] 2016-04-28 07:03
Hello,
i think removing -density 300 is equal to set -density 72 that is why if your original pdf is created at 300 dpi, removing the attribute is not an option.
Modification of the documentation is a good solution and probably the best because density is complicated to use.  
but i think a better way would be to get the density from the PDF (in images metadata or pdf metadata?) and set the density attribute with the same value when extracting the image, i searched the web to see if this is possible but did not found a real solution. 
this link is interesting:
http://superuser.com/questions/479197/i-want-to-change-dpi-with-imagemagick-without-changing-the-actual-byte-size-of-t

**Comment by polo2ro** [comment] 2016-04-28 07:35
I have checked out the identify command with a pdf generated at -density 300 and also the bad pdf linked in my upper post, on the two pdf i have a density at 72 from the metadata (probably never set by imagemagick).
but the interesting value is the size in inch:

```
$ identify -verbose good.pdf[0] | grep Print
  Print size: 8.26389x11.4583
$ identify -verbose bad.pdf[0] | grep Print
  Print size: 34.4444x47.7361
```
The size of the bad PDF is not A4 because i merged A4 300 dpi images in a 72 dpi document, this make sense

**Comment by danielquinn** [comment] 2016-04-28 07:42
Yeah it looks like we could use `identify -verbose <filename> | grep Resolution` to get the DPI (which was 72 for all of my PDFs), but I'm not sure what would happen for a version of `identify` installed with another language.  Ie. `Resolution` maybe `Ανάλυση`, so `grep` would fail in this case.

To get back to your specific problem though, I don't think that the above would help.  This is what happens when I try to parse your sample PDF for resolution:

```bash
$ identify -verbose /tmp/Scan\ -\ 20160427210020.pdf | grep Resolution
  Resolution: 72x72
  Resolution: 72x72
```

If I were to apply the logic of "if resolution <300, set `-density 300`" then we'd still trigger the warning.  More to the point, given that it's just a warning and the pnm is still being generated, and the OCR is running against the generated image, I think the problem is possibly that of the quality of the scan.  The sample you've provided here for example has a lot of "ghosting" as if there's another document faded over top (or maybe on the other side of the page?) and that maybe confusing the OCR.

Put another way, I don't think that the reason the OCR engine can't find any text is because of this warning.  Unless `convert` is generating a blank white document, it's probably either (a) the quality of the scan, or (b) the quality of the generated image.  Perhaps setting `-depth 16` would be a better choice?

I've just run some tests and converted your sample PDF with the following commands:

    $ convert -density 300 -depth 8 -type grayscale Scan\ -\ 20160427210020.pdf convert.pnm

![before-unpaper](https://cloud.githubusercontent.com/assets/218205/14878661/d0f98c9c-0d1c-11e6-9ec6-e27bff635b88.png)

    $ unpaper convert.pnm convert.unpaper.pnm

![after-unpaper](https://cloud.githubusercontent.com/assets/218205/14878662/d0fe7f86-0d1c-11e6-858a-c37fb88953a9.png)

Obviously, I converted from pnm to png and scaled everything down to 1000px wide so it'll fit here, but you get the idea.  I don't see how the DecompressionBombWarning or the DPI is the problem here.

**Comment by polo2ro** [comment] 2016-04-28 09:39
i thinks the fact that i got no content is related to the fact that my file was too large and scaled up. on the second document (the one in attachment) i got some text detected but poorly despite the DecompressionBombWarning message.
When i got no text i suspect this is a performance problem of my small nas because the scaled up pnm take hours to process.
i think we should close the issue and add a notice in the doc to recommend pdf in A4 300dpi.

**Comment by danielquinn** [comment] 2016-04-29 13:55
Alright, I won't close this but I'll tag it as `enhancement` and leave it open until I can get around to adding this special case to the Troubleshooting section of the docs.

**Comment by danielquinn** [comment] 2016-04-30 12:58
Alright I've updated the Troubleshooting page.  I think that should be enough so I'm closing this issue.  If you think that it needs something more though, feel free to re-open.

**Closed by danielquinn** 2016-04-30 12:58 UTC
Labels: enhancement
