### ISSUE TITLE
coulour code instad of colour displayed in tag view

### ISSUE THREAD

**Issue by inos-github** [danielquinn/paperless#275] opened 2017-12-17 09:01 UTC
on the 'Tags' view, the colour codes instead of the colours itself are displayed in the colour drop-down menu as well as in the Filter by colour menu.

paperless is running without any proxy on a standard debian 9 (armhf), cloned from git version 0.8.0. Same behaviour on master branch.

**Comment by danielquinn** [comment] 2017-12-18 10:40
Yeah this isn't a bug so much as a lack-of-feature.  Standard HTML select boxes aren't all that good at letting you include something that's not plain text, so doing something nice like having colours instead of hex codes requires some js/css hackery.

If you'd like to contribute some code to make this work, I'm happy to merge it, but I just don't have the time to experiment lately.  I can tell you where to start looking though: [Select2](https://select2.github.io/) + telling the Django Admin to include custom CSS/JS code.

**Comment by danielquinn** [comment] 2018-01-22 10:56
Closing as duplicate of #284.

**Closed by danielquinn** 2018-01-22 10:56 UTC
Labels: I won't do it but contributions welcome
