### ISSUE TITLE
Error consuming documents

### ISSUE THREAD

**Issue by ekw** [danielquinn/paperless#170] opened 2017-01-01 22:23 UTC
I get this error when paperless consumes documents:
```
Consuming /.../Paperless/Watch/DS1306.pdf
Generating greyscale image from /.../Paperless/Watch/DS1306.pdf
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/paperless/src/documents/management/commands/document_consumer.py", line 56, in handle
    self.loop()
  File "/opt/paperless/src/documents/management/commands/document_consumer.py", line 66, in loop
    self.file_consumer.consume()
  File "/opt/paperless/src/documents/consumer.py", line 123, in consume
    imgs = self._get_greyscale(tempdir, doc)
  File "/opt/paperless/src/documents/consumer.py", line 168, in _get_greyscale
    doc, pnm,
  File "/opt/paperless/src/documents/consumer.py", line 401, in run_convert
    subprocess.Popen(args, env=environment).wait()
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1379, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.4/os.py", line 770, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not NoneType
```
This happens on every document I tried so far, including this one, as an example:
http://datasheets.maximintegrated.com/en/ds/DS1306.pdf

Any idea what I'm doing wrong? I followed the "Standard (Bare Metal)"  steps in the setup docs.

**Comment by danielquinn** [comment] 2017-01-01 22:39
Good news!  I can reproduce this.  Gimme a few minutes and I'll see about fixing it.

**Comment by ekw** [comment] 2017-01-01 22:50
Thanks.  Looking into it as well.  Seems like I need to set the environment variable "PAPERLESS_CONVERT_BINARY" to something, somewhere.

**Comment by danielquinn** [comment] 2017-01-01 22:50
Thanks for finding and reporting so quickly!  The problem was that `CONVERT_BINARY` didn't have a default value anymore after I removed some deprecated code.  I didn't notice since I have that value set in my local environment.

Please do a `git pull` and give it another shot.  The default is now just `convert` which means it will look for `convert` in your `$PATH` and use whatever it finds first.  If you have convert living somewhere strange, you should define `PAPERLESS_CONVERT_BINARY` in `/etc/paperless.conf`.

I'll close this now, but if the problem isn't fixed for you, pleas re-open.

**Closed by danielquinn** 2017-01-01 22:50 UTC
