### ISSUE TITLE
Data loss when exporting documents with duplicate titles

### ISSUE THREAD

**Issue by tikitu** [danielquinn/paperless#51] opened 2016-02-19 08:02 UTC
The export script writes documents into a directory without checking for name collisions. This means that if I upload two documents with the same title, they will produce distinct entries in the database, but the export will clobber one of them.

I'm happy to tackle fixing this (I have quite some more experience with python and django than with docker :-) ), but wanted to get your pre-approval for the approach I would take. I thought to add a timestamp prefix to the export, so that files come out looking like `2016-02-13T23:15:02Z - Title - tag,tag.pdf`. It's not 100% watertight, but it seems pretty much good enough to me. It also implies the consumer has to recognise this format -- that has one nice side effect, namely that exporting docs and re-importing them will also preserve the timestamps at which they were *originally* imported.

If you prefer a different approach, I'm happy to take it on if you can give me a sketch, or to brainstorm alternative ideas here. I actually need something like this, because one of my use cases for paperless is storing documents that come in at regular intervals and will always get the same name (e.g. the electricity bill).

* [ ] Are filenames with `.isoformat()` datetimes scp-compatible? (There is some concern about the `:` character.)

**Comment by danielquinn** [comment] 2016-02-19 09:10
Ouch.  I hope you didn't lose any documents thanks to this bug!  Thanks for noticing and for offering to fix it, since I'm really busy for the next couple days.

Regarding your proposed fix, the timestamp is actually being exported appropriately by [re-writing the creation time on the document](https://github.com/danielquinn/paperless/blob/master/src/documents/management/commands/document_exporter.py#L52), so including it in the name is sort of redundant.  Additionally, messing with the name of the file on output means that importing it later would involve changing the name of the document in the database.  That is to say, a document with the name `2016-02-13T23:15:02Z - Title - tag,tag.pdf` would have a sender of `2016-02-13T23:15:02Z`.

I think I'd rather go the route of specifically changing the title to something that doesn't conflict.  So if `Sender - Title - tag,tag,tag.pdf` already exists, we could change it to `Sender - Title 2 - tag,tag,tag.pdf`.

Perhaps a better solution, albeit a more complicated one, would be to extend the naming regex to account for conflict addendums like ` 2`, so the output file would look like `Sender - Title - tag,tag,tag 2.pdf`.  This has the advantage of exported files being imported exactly like you'd expect, but it would mean fiddling with the name matcher on import.  Thankfully, this is one of the few places for which we have [tests](https://github.com/danielquinn/paperless/blob/master/src/documents/tests/test_consumer.py).

So unless you have a strong preference, I'm leaning toward the regex-changing option since that provides the most stable interface between import & export.  What say you?

**Comment by tikitu** [comment] 2016-02-19 09:35
Nothing lost: I discovered it because I was sending the same document through again and again for testing :-)

I'm fine with changing the doc title or adding filename `.2.pdf` addendums if that's your preference. One more pitch for my alternative though: what I had in mind is changing the import regex specifically so that it treats a filename-initial timestamp *not* as Sender, but writes it into the database as a (faked) import time ("Created" date) instead. (That's what I mean by "the consumer has to recognise this format". Of course I would also update docs and tests to match.)

That means the document Title and Sender are exactly preserved through an export/import cycle (the filenames do change: the exported filename includes the timestamp whether the original file did or not), and as well that if you import your tax filing on December 27th 2015, export the files on January 5th 2016 and make a new import of everything on January 6th, that the documents in the newly-imported database will still have a "Created" date of December 27th. (I think this is a desirable property of an export/import cycle, but I won't argue this point if you disagree: in that case we definitely should go with conflict addendums instead.)

I'll happily take on either option over the weekend: up to you which way it goes.

**Comment by tikitu** [comment] 2016-02-19 09:38
NB: my scheme means that if you export your files then import them into the *same* database, you again get filename collisions on export. I'm half-convinced that's ok, since in that scenario the colliding files are genuinely *the same file* (in the database twice), but again that should be your call rather than mine I think.

**Comment by danielquinn** [comment] 2016-02-19 11:46
It's not entirely unreasonable to assume that there would be duplicate entries in a production system.  Think of the case of:

    Sender: None
    Title: Lunch Receipt
    Tags: expenses

Such a record could quite reasonably exist multiple times, so I definitely consider this a bug worth solving.

As for the suggestion of including the time, I'm still confused as to why setting the created time on the file is insufficient.  The current export/import process is:

Export:

1. Decrypt the file and save it in the format `Sender - Title - tag,tag.format`
2. Set the creation time of the file to the `Document.created`

Import (Consume):

1. Parse the file name for any data it can use.
2. Set Document.created to the file's created time.

How would putting the creation time into the name help here?

**Comment by tikitu** [comment] 2016-02-19 12:03
Aha! I was missing one detail: I didn't realise that Document.created is set to the *creation time of the incoming file*, and not the timestamp at which the consumer starts processing up the file. (I've been copying files into the `/consume` directory, so these two times are very similar in all the cases I've seen so far.) I should start (*ahem*) reading some of your code...

In that case my scheme *doesn't* help for the Document.created values after an export/import cycle: they're already fine. My scheme only fixes the duplicate entries, and it doesn't do that 100%.

I'm convinced: my preference is now for a version suffix to avoid duplicates, something like `Sender - Title - tag,tag,tag.version.pdf`. (And skip the `.version` unless it's needed.) The example you gave is a good reason not to include it in Document.title I think: `Lunch Receipt 127` is just too depressing.

**Comment by pitkley** [comment] 2016-02-19 13:36
Just to throw another spoke in the wheel: while it is true that the import time gets exported as the modified time of the file and imported as well, if you start copying those exported files around for backup, you will most probably lose that information.

Linux `cp` needs to be [specifically instructed](http://man7.org/linux/man-pages/man1/cp.1.html) to keep the dates, `scp` [too](http://linux.die.net/man/1/scp), the base `ftp` utility apparently can't do it [out of the box](http://linux.die.net/man/1/ftp). And as soon as you are crossing different file and/or operating systems, those dates will probably be lost for good.

My preference would be for the timestamp to be an optional part of the filename, and if it is missing, use the old method of taking the modification date.

**Comment by danielquinn** [comment] 2016-02-19 14:01
Yeah I hadn't thought about the user copying files around *after* the export.  And here I thought I was being clever with putting the time in the file metadata.

Alright then, now the problem is writing a regex to handle optional timestamp values.  I think I'd prefer to put it to the right, since it's the least likely bit of data someone is going to have on-hand when manually naming the file.  I rather like the output of `.isoformat()`, but I'm a little concerned about the existence of `:` in the file name.  I know it's legal on Unix systems, but it might present a problem for things like scp no?

Anyway, here's the proposed list of accepted formats:

* `Title.extension`
* `Sender - Title.extension`
* `Sender - Title - tag,tag,tag.extension`
* `Sender - Title - tag,tag,tag - YYYY-MM-DDTHH:MM:SS.SSSSSS`
* `Sender - Title -  - YYYY-MM-DDTHH:MM:SS.SSSSSS`

The time should be assumed to be UTC.

I'm not sure if I like the "optionalness" of both the tags and the time, but I'm out of ideas regarding how to best handle this.  I'm open to ideas.

**Comment by tikitu** [comment] 2016-02-19 14:26
Without having looked at any code yet, I don't see a problem with allowing the timestamp optionally on *any* of the other formats. (Which is necessary if we're going to solve the duplicates bug, because a file that comes in with any of the other formats needs to come out with a timestamp attached.) There are some subtleties, but I think I can make something that makes sense. I might go TDD and get you to check over a list of unit tests to make sure I didn't miss anything big.

I would be inclined to put the timestamps on the left, which gives you a visual ordering that makes sense and has a fixed-width prefix, but I'm not gonna make a scene about it.

About the `:` and scp I have no idea. I would default to `.isoformat()`, but it should be easy enough to change that if needed.

**Comment by pitkley** [comment] 2016-02-19 14:28
While the `:` is legal and can most probably somehow be escaped for use with at least `scp`, it might be rather tedious.

> `Sender - Title - - YYYY-MM-DDTHH:MM:SS.SSSSSS`

@danielquinn The difference in format of the tags and the time is definitely significantly enough that we wouldn't have to make the tags optional by having two `-` in a row. I don't know if you made this decision in regards to the regular expression, but here is a working **single** regular expression which covers all the following examples:

```regex
^((?P<sender>\w+)\s*-\s*)?(?P<title>\w+)(\s*-\s*(?P<tags>[\w,]+))?(\s*-\s*(?P<date>.{26}))?\.(?P<ext>.*)$
```

    Title.extension
    Sender - Title.extension
    Sender - Title - tag,tag,tag.extension
    Sender - Title - YYYY-MM-DDTHH:MM:SS.SSSSSS.extension
    Sender - Title - tag,tag,tag - YYYY-MM-DDTHH:MM:SS.SSSSSS.extension

See it [live and in action](http://pythex.org/?regex=%5E((%3FP%3Csender%3E%5Cw%2B)%5Cs*-%5Cs*)%3F(%3FP%3Ctitle%3E%5Cw%2B)(%5Cs*-%5Cs*(%3FP%3Ctags%3E%5B%5Cw%2C%5D%2B))%3F(%5Cs*-%5Cs*(%3FP%3Cdate%3E.%7B26%7D))%3F%5C.(%3FP%3Cext%3E.*)%24&test_string=Title.extension%0ASender%20-%20Title.extension%0ASender%20-%20Title%20-%20tag%2Ctag%2Ctag.extension%0ASender%20-%20Title%20-%20YYYY-MM-DDTHH%3AMM%3ASS.SSSSSS.extension%0ASender%20-%20Title%20-%20tag%2Ctag%2Ctag%20-%20YYYY-MM-DDTHH%3AMM%3ASS.SSSSSS.extension&ignorecase=0&multiline=1&dotall=0&verbose=0). The named groups extract the information we want regardless of the filename, if the format is incorrect the expression will not match at all.

**Comment by pitkley** [comment] 2016-02-19 14:31
Oh, yeah, and it also matches the following correctly:

    Title - tag,tag,tag.extension
    Title - YYYY-MM-DDTHH:MM:SS.SSSSSS.extension
    Title - tag,tag,tag - YYYY-MM-DDTHH:MM:SS.SSSSSS.extension

The sender thus can be completely optional.

**Comment by danielquinn** [comment] 2016-02-19 14:50
That's a nifty tool!

There's a problem with your regex though, it doesn't allow for spaces or hyphen's in the sender or title.  I couldn't figure out how to do this in a single regex, so that's why I used that multi-tiered approach.  I tried this for example:

    ^((?P<sender>[\w\- ,.']+)\s*-\s*)?(?P<title>[\w\- ,.']+)(\s*-\s*(?P<tags>[a-z\-,]+))?(\s*-\s*(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}))?\.(?P<ext>.*)$

But that just ended up putting `This is the Sender's name - This is the Title` into the `sender` field.  Do you know how we could do this in just one regex?  'Cause that'd be nifty :-)

Also, if we're going to put the date in the name, and if your regex-foo here will allow optional fields in the name to live anywhere in the string, I think that @tikitu's suggestion of putting the date at the start of the file name is probably best.  Otherwise, if we have to go with the multi-tiered method I'm currently using, and we can't get that to work with dates on the left, it's fine to put it at the right.

**Comment by tikitu** [comment] 2016-02-19 14:58
I have a gentle preference for a multi-tiered approach anyway, since it's likely to be more maintainable than a single regex. That's still without looking at any code yet though!

How about I put something together this weekend and see what y'all think of it? I don't mind iterating a few times to get something everyone is happy with.

**Comment by pitkley** [comment] 2016-02-19 15:02
While you are correct in that I missed common symbols (especially spaces!), supporting hyphens in sender and title will never be possible.

    This - is - my - file - name - tag.ext

Can you tell me which part is the sender, which the title and if `tag` is actually a tag or part of the title? A regex can't either, since this is ambiguous.What we could do is change the separator to maybe two hyphens in succession or something similar.

But no matter what we do, if multiple or a single regex, we can't get rid of ambiguities if we keep the seperator so common.

**Comment by danielquinn** [comment] 2016-02-19 15:08
The idea is that `Sender-name` is acceptable, while `Sender - name` is not, so the separator is ` - ` rather than `-`.  I'm not opposed to changing the separator to ` -- ` though, if you think that that's more maintainable.

**Comment by pitkley** [comment] 2016-02-19 15:19
> so the separator is `<space>-<space>`

Oh, right, [that's possible](http://pythex.org/?regex=%5E((%3FP%3Csender%3E(%5B%5Cw%2C.%20%5D%7C(%5B%5E%5Cs%5D-))%2B)%5Cs%2B-%5Cs%2B)%3F(%3FP%3Ctitle%3E(%5B%5Cw%2C.%20%5D%7C(%5B%5E%5Cs%5D-))%2B)(%5Cs%2B-%5Cs%2B(%3FP%3Ctags%3E%5B%5Cw%2C%5D%2B))%3F(%5Cs%2B-%5Cs%2B(%3FP%3Cdate%3E.%7B26%7D))%3F%5C.(%3FP%3Cext%3E.*)%24&test_string=Mr.%20Sender-Name%20-%20Title%20with-dashes.extension%0AMr.%20Sender-Name%20-%20Title%20with-dashes%20-%20tag%2Ctag.extension%0AMr.%20Sender-Name%20-%20Title%20with-dashes%20-%20YYYY-MM-DDTHH%3AMM%3ASS.SSSSSS.extension%0AMr.%20Sender-Name%20-%20Title%20with-dashes%20-%20tag%2Ctag%20-%20YYYY-MM-DDTHH%3AMM%3ASS.SSSSSS.extension&ignorecase=0&multiline=1&dotall=0&verbose=0).

While it certainly looks ugly like that, in actual code one can split it up into multiple identical parts which can then be interpolated into the whole regex to have smaller parts to actually maintain.

This way one regex might be easier than multiple, but I haven't actually thought about how to set up multiple regexes to cover what we want to do here correctly.

**Comment by danielquinn** [comment] 2016-02-19 15:27
Clearly the regex Force is strong with you.  Can you rework it to handle the following?

* Place the date at the start of the string
* Be more restrictive with the date format `[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}`
* Be more restrictive with the tag format `[a-z\-,]+`

Typically, I agree with @tikitu that reability is more important, but when we're talking about a regex, I'd much rather implement string matching in one place rather than repeat it in a series of if/else statements trying to do the work of a regex.  In other words, if it's a regex problem, I'd prefer it to be implemented as a regex.

However, I'd want to make sure that it doesn't violate the 80character limit, so it should be laid out nicely for readability, perhaps broken into 1 line per fragment: sender, title, tags, time.

If @pitkley can write the regex, can @tikitu implement it and modify the existing tests?

**Comment by pitkley** [comment] 2016-02-19 15:32
> perhaps broken into 1 line per fragment: sender, title, tags, time.

That is what I was thinking about in regards to "smaller parts".

> Place the date at the start of the string

Will do.

> Be more restrictive with the date format

I only used `\w` as a start since `YYYY` doesn't match `\d{4}` ;).

> Be more restrictive with the tag format `[a-z\-,]+`

Will do.

---

I'll probably get this one done today, so it should be ready by the time @tikitu wants to start :+1:

**Comment by tikitu** [comment] 2016-02-19 15:36
I can't promise I'll use it! I haven't looked at code yet, and I also don't have a clear list of edge cases in mind regarding fallbacks if fields are missing or ambiguous. I would prefer the chance to tackle the original issue and see what comes of that: if someone wants to refactor the regex handling later, that can be a separate PR. (I *will* make an effort to write tests that don't care whether we're one-big-regexing or iteratively-consuming.)

**Comment by danielquinn** [comment] 2016-02-19 15:39
Alright, @tikitu go ahead and submit a PR for what you can.  I'll merge it on my end in a temporary branch and then include @pitkley's regex-foo to get it all sorted.  Hopefully everything will be ready by early next week.

In terms of tests, [note that we already have a good start on handling file name parsing](https://github.com/danielquinn/paperless/blob/master/src/documents/tests/test_consumer.py) so please use that as a starting point.

**Comment by the01** [comment] 2016-02-19 16:16
You might be fine on linux with that file naming scheme, but windows is not as gracious.
I know you are targeting linux, but since you are already considering backups - windows might play a role here. Also, I, for example,use samba mounts to access documents from all my devices at home (windows, osx,..) and test:file.txt kind of ends up as T8S6CH~R.TXT when viewed from explorer.

**Comment by danielquinn** [comment] 2016-02-19 16:26
Ah Micros~1, still giving me reason to hate them, even decades after I switched to Linux.

Is there an ISO standard way of representing time that's Windows friendly in a file name?  I know UNIX time stamps would work, but they're not human-friendly, so I'd rather avoid that if possible.  In a worst-case scenario, I suppose we could go with a personal favourite: `YYYYMMDDHHMMSSSSSSSS`.

**Comment by the01** [comment] 2016-02-19 16:42
ah, 20160219164041, what could be more obvious to work with?

But sarcasm aside, I think 20160219_164041 would actually approach borderline readability?

**Comment by danielquinn** [comment] 2016-02-19 16:45
So I did a quick search for ISO time formats and this looks like the [official one](https://en.wikipedia.org/wiki/ISO_8601) that doesn't use `:`: `20160219T032607Z`  There's no miliseconds, but I think that's fine for our purposes.

**Comment by the01** [comment] 2016-02-19 16:51
oh, I accidentally got close :smile:
I agree with the miliseconds. It's mostly info for humans and we tend to ignore that part anyway (my scanner sets it to 0 too)

**Comment by pitkley** [comment] 2016-02-19 17:16
The way I see it, the separators we have that get us the most compatibility are hyphens and underscores. If we try to make it more readable for humans, something like `2016-02-19_16-40-41` might be interesting, or a `T` instead of the `_`.

If we don't care about the user being able to read the date, unix epoch would be the absolut easiest to deal with.

**Comment by danielquinn** [comment] 2016-02-19 17:22
I don't want to start using our own standards so long as an established one does the job, hence my preference for ISO8601 and `YYYYMMDDHHMMSSZ`.  It's human-friendly enough that it's obvious to people that it's a date/time and easy enough to parse/generate for machines.  In fact, Paperless already includes the `dateutil` package, so parsing ISO8601 should be easy.

**Comment by pitkley** [comment] 2016-02-19 19:16
Just gonna leave [this](https://gist.github.com/pitkley/e3c5f7831dda31d3b864) here! If an example is missing or I messed one of the dicts up, please let me know :+1:

**Comment by tikitu** [comment] 2016-02-21 21:05
(Just so you don't think I disappeared off into the dark and forgot about this: I ended up not having much time this weekend, so I wrote some simple tests but have not started on non-test code yet. Will keep working on it in evenings this week.)

**Comment by danielquinn** [comment] 2016-02-21 21:14
Oh dude, this is all voluntary so don't feel bad if you run low on time.  @Pitkley's contribution above looks good, so please make use of it of you can.  I'm going to donate my time to fixing the logging, so there shouldn't be overlap.

**Comment by danielquinn** [comment] 2016-02-28 17:50
So I've been doing some thinking about this whole process and I think I've got the right idea now.  Instead of trying to cram everything into the file name, I'm thinking I'll write an importer/exporter that looks into a directory for a list of PDFs and a `manifest.json` file that contains all of the metadata for each of the files.  This would mean that people can put any character they like into the sender and title (including for example `/`, `:`, `&` etc.) without having to worry about breaking import/export, and it would also mean that it could support future metadata without having to revisit this issue.

So, @tikitu, I hope you haven't been hacking at this too long, 'cause unless someone can give me a terribly compelling reason not to go this `manifest.json` route, I think I'll start poking at that this week.

For reference, this problem is bleeding into [this other issue](https://github.com/danielquinn/paperless/issues/58#issuecomment-186701504) in which someone else wanted to propose a "categories" attribute as well as favourite searches etc.

**Comment by tikitu** [comment] 2016-02-29 20:54
Makes sense. I haven't got very far, don't worry! I do have a small refactoring and some tests that sound like they would still be useful for your new direction: I'll tidy them enough to give you a PR Any Day Now (tm).

**Comment by danielquinn** [comment] 2016-03-04 23:32
Exciting news!  This should no longer be a problem now that the exporter has been replaced (see #70) so I'm closing this issue.

**Closed** 2016-03-04 23:33 UTC
Labels: bug, enhancement, help wanted
