### ISSUE TITLE
CSS: document topics and checkboxes not aligned?

### ISSUE THREAD

**Issue by xkpd3** [danielquinn/paperless#272] opened 2017-11-20 17:06 UTC
Hi,

Is it normal that the document title and the checkboxes are overlapping?

![image](https://shell.srv.hagen.coffee/~sdk/screenshots/2017-11-20_18-00-16.png)

**Comment by danielquinn** [comment] 2017-11-28 10:54
Nope, that's not normal, but my guess is the problem is that those file names are quite long, so it's pushing the text over the box.  This might be fixed by setting the width of the div containing the checkbox to a fixed value rather than letting the browser decide.

What browser is this?

**Comment by xkpd3** [comment] 2017-11-29 10:32
Okay, thanks for the hint. I'll try to fix it via css.  It thought maybe be there is something wrong with my setup.

I tried Firefox, Chrome and Luakit (webkit2 based browser). The screenshot above was taken with Firefox.

**Comment by danielquinn** [comment] 2018-01-06 15:59
Ok this is now fixed in `master`.  It turns out that this was only happening at some resolutions, so I never saw it.  The CSS I'm using now is a lot cleaner.  Thanks for the heads up.

**Closed by danielquinn** 2018-01-06 15:59 UTC
