### ISSUE TITLE
RFE: optionally insert OCR result in pdfs

### ISSUE THREAD

**Issue by Moini** [danielquinn/paperless#288] opened 2018-01-19 22:24 UTC
It would be useful if the resulting pdfs could contain the OCR result in an invisible text layer (or even be updated when the text in the db changes, but that might be harder, because without OCR, it's not going to know where to insert the changed text).

**Comment by danielquinn** [comment] 2018-01-22 10:47
Closing this as a duplicate of #19.  It's a common request, but one I don't personally have the skills to do.  If you have ideas though, I'm happy to accept the help :-)

**Closed by danielquinn** 2018-01-22 10:47 UTC

**Comment by Moini** [comment] 2018-01-22 12:16
Oops. Thank you!
