### ISSUE TITLE
Deleting correspondent cascades the delete to all assigned documents

### ISSUE THREAD

**Issue by thomasbrueggemann** [danielquinn/paperless#235] opened 2017-06-05 18:19 UTC
Not a bug report, but I was quite surprised that when I deleted a correspondent all documents assigned to that correspondent were not available anymore. This could potentially lead to some unexpected/unintended behaviour. 

I just wanted to get rid of the correspondent - I like to only have some major correspondents listed and not every document has a correspondent assigned.

What do you think?

**Comment by ddddavidmartin** [comment] 2017-06-11 06:08
I agree.

Also, is there currently a way of deleting correspondents without removing the documents as well?

**Comment by danielquinn** [comment] 2017-06-11 11:33
That seems like reasonable behaviour.  Django's default behaviour is to cascade deletes, which is why this is happening, but it can be prevented [with an argument to to the field definition](https://stackoverflow.com/questions/3651775/django-remove-on-delete-cascade-behaviour-of-django).

If one of you wants to issue a PR with this (and a test!) then I'll merge it.  Otherwise I'll try to get to this soon.

**Comment by ddddavidmartin** [comment] 2017-07-05 08:56
I had a quick look at this, and applying @danielquinn's approach would be as follows and it seems to work fine on my end.
```
diff --git a/src/documents/models.py b/src/documents/models.py
index 54f45ae..bc34eac 100644
--- a/src/documents/models.py
+++ b/src/documents/models.py
@@ -172,7 +172,8 @@ class Document(models.Model):
     TYPES = (TYPE_PDF, TYPE_PNG, TYPE_JPG, TYPE_GIF, TYPE_TIF,)
 
     correspondent = models.ForeignKey(
-        Correspondent, blank=True, null=True, related_name="documents")
+        Correspondent, blank=True, null=True, related_name="documents",
+        on_delete=models.SET_NULL)
 
     title = models.CharField(max_length=128, blank=True, db_index=True)
 
```

See https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ForeignKey.on_delete.

I'm not sure yet about an appropriate test though.

**Comment by danielquinn** [comment] 2017-07-15 18:42
Thanks for your patience on this guys.  I've written a fix (and a corresponding test) and it's now in `master`.

**Comment by thomasbrueggemann** [comment] 2017-07-15 18:50
Thanks, Daniel!

**Comment by HorayNarea** [comment] 2017-07-16 20:39
The same issue is (still) present with tags

**Comment by danielquinn** [comment] 2017-07-17 09:48
That's odd, since an n:1 relationship (like documents have with tags) should never result in a cascade delete.  I'll re-open this and see if I can write a test for it.

**Comment by danielquinn** [comment] 2017-07-17 10:04
That's the expected behaviour.  If you delete a tag, then it, and all associations with it should go, but the documents to which it was linked should not be removed.  So am I to understand that this is a non-issue?

**Comment by HorayNarea** [comment] 2017-07-17 21:49
@ddddavidmartin is right, i misinterpreted the warning. Sorry.

**Comment by danielquinn** [comment] 2017-07-18 09:19
K cool.  Re-closing now.

**Closed by danielquinn** 2017-07-18 09:19 UTC
