### ISSUE TITLE
Docker: wrong folder permissions for /consume

### ISSUE THREAD

**Issue by dev-rke** [danielquinn/paperless#267] opened 2017-10-30 15:15 UTC
Hi @danielquinn, hi @pitkley,

When starting up the application via docker-compose i get the following warning:
```
chgrp: cannot access ‘’: No such file or directory
Changing group of export directory:
  
failed.
2017-10-30T13:40:13.134346296Z 
Either try to set it on your host-mounted directory
directly, or make sure that the directory has `o+x`
permissions and the files in it at least `o+r`.
chmod: cannot access ‘’: No such file or directory
Changing group permissions of export directory:
  
failed.
2017-10-30T13:40:13.134371036Z 
Either try to set it on your host-mounted directory
directly, or make sure that the directory has `o+x`
permissions and the files in it at least `o+r`.
```

This seems to lead to the following issue, that the consumer dies when files cannot be removed after parsing:
```
Starting document consumer at /consume
Parsers available: RasterisedDocumentParser
Consuming /consume/image.jpg
Processing sheet #1: /tmp/paperless/paperless6vul_yxo/convert-0000.pnm -> /tmp/paperless/paperless6vul_yxo/convert-0000.unpaper.pnm
OCRing the document
Parsing for eng
Completed
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 57, in handle
    self.loop()
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 67, in loop
    self.file_consumer.consume()
  File "/usr/src/paperless/src/documents/consumer.py", line 139, in consume
    self._cleanup_doc(doc)
  File "/usr/src/paperless/src/documents/consumer.py", line 223, in _cleanup_doc
    os.unlink(doc)
PermissionError: [Errno 13] Permission denied: '/consume/image.jpg'
```

When i attach a shell to the consumer container and ```cd /consumer``` to list directory contents, the folder looks like this:
```
drwxr-xr-x  2 root      paperless 4.0K Oct 30 14:43 .
drwxr-xr-x 71 root      root      4.0K Oct 30 13:40 ..
```

When i change the owner of the /consume folder from root to paperless using ```chown paperless:paperless .``` it works like a charm.
It also works like a charm, when i allow the directory to be written by the group using: ```chmod 775 .```

I tried the behaviour before and afterwards with different file types (pdf, png and jpg), before this change the container always died, afterwards it worked always and the container keeps running.
So the application does not have enough rights to do file modifications in that directory.

Regarding the application itself: I think the consumer should not die, but it should throw a warning.
Regarding the docker stuff: the owner of the consume folder should be set as well or the folder permissions should be changed to be writable for the group.

**Environment**:
* Ubuntu 16.04
* Docker 17.09.0-ce
* i am using docker-compose.yml and docker-compose.env

**Comment by pitkley** [comment] 2017-10-30 19:19
Thanks for the report. I've tried to trace the issue, because we have code logic which tries to [set the permissions on both](https://github.com/danielquinn/paperless/blob/bd67b53d50b494854e1e4423d7efcf3d2cea449e/scripts/docker-entrypoint.sh#L17-L43) the consume and the export directory. Though this requires the environment variables `$PAPERLESS_CONSUMPTION_DIR` and `$PAPERLESS_EXPORT_DIR` to be set -- which by default I don't think they are.

In fact, I receive the same warning messages you posted at the start of your issue. I just don't experience any problems since my mounted directories already had the permissions set.

Can you try to add the following to your `docker-compose.env` and verify if your issues disappear?

```env
PAPERLESS_CONSUMPTION_DIR=/consume
PAPERLESS_EXPORT_DIR=/export
```

-----

> Regarding the application itself: I think the consumer should not die, but it should throw a warning.

If the consumer can not do it's work because of permission issues, why should it not die?

> Regarding the docker stuff: the owner of the consume folder should be set as well or the folder permissions should be changed to be writable for the group.

This is done, as mentioned above, it's just that the environment variables don't seem to be set up correctly (which is a fault on our side, both in the script and the documentation).

**Comment by dev-rke** [comment] 2017-10-31 01:27
Hi @pitkley,

thanks for you reply.

> If the consumer can not do it's work because of permission issues, why should it not die?

It seems the consumer works well (because the indexing worked), but the consumer dies.
So i wonder, why it dies and not throws a warning to the user.

> This is done, as mentioned above, it's just that the environment variables don't seem to be set up correctly (which is a fault on our side, both in the script and the documentation).

Hm, i see there are some default values defined in the Dockerfile.
Are they "dropped" when using an environment file?

Inside of the container "env" provides 
```
PAPERLESS_CONSUMPTION_DIR=/consume
```

But why there is no "/export" folder?
Shouldn't it be created automatically by the Dockerfile?
```
# Set export directory
ENV PAPERLESS_EXPORT_DIR /export
RUN mkdir -p $PAPERLESS_EXPORT_DIR
```
should generate the folder. Might it be, that the CI uses a different Dockerfile?


PS:
:D 
I think i might have found a source for that issue:
the travis branch
https://github.com/danielquinn/paperless/blob/fix/travis/Dockerfile
does not contain the PAPERLESS_EXPORT_DIR-Environment variable in its Dockerfile...

Why not building from master?

**Comment by dev-rke** [comment] 2017-10-31 01:38
Ok, i just tried adding the definition in the .env-file:
```
chgrp: cannot access ‘/export’: No such file or directory
Changing group of export directory:
  /export
failed.
```
Consumer container still dies, as the folder rights for the consume folder are wrong again.

The export directory does not exist, as docker-entrypoint.sh does not create the provided folder name.
In the travis-branch-Dockerfile the folder is not created, so it cannot change the group of it, this makes sense.
I think the solution is to create the folder and set folder permissions not inside of the Dockerfile, but this should be done inside of docker-entrypoint.sh to also handle other directories specified by the user.

Another approach: don't let the user change the consume and export directories and define them hard.
We are using docker, you can mount anything to anywhere, so there might be no reason to change them. ;-)

**Comment by pitkley** [comment] 2017-10-31 14:40
Thanks for the further input, I think I have tracked down the issues.

1. The Docker image you are using is probably [`pitkley/paperless`](https://hub.docker.com/r/pitkley/paperless), which is built from a [separate repository](https://github.com/pitkley/docker-paperless). (We never came around to move it over to `danielquinn/paperless` or build `pitkley/paperless` from this repository.)

    I have now [updated](https://github.com/pitkley/docker-paperless/commit/88d1fceda9df6e259f7f9e4a6e06febbbe05a267) the `Dockerfile` which that image was built from to include setting up the export-directory. (Although this is separate from the main issue you experience.)

2. I have reproduced the issue you have received. As you have determined the consumer dies once it tries to remove a successfully consumed document.

    The reason it removes it in the first place is because Paperless does not keep track of already consumed files, at least not across restarts or for successfully consumed files. So every time you would start Paperless, it would consume every file in the `/consume` directory.

    I think the solution is as you have proposed: change the permissions of the consumption-directory to include the write-permission for the group, such that the file can be deleted. I have [created a PR](https://github.com/danielquinn/paperless/pull/268) to add this permission on startup.

Once @danielquinn merges #268, I will trigger a rebuild of the Docker Hub image, such that this change is included. I hope that this fixes your issues!

**Comment by dev-rke** [comment] 2017-10-31 17:09
1. Yeah, this is the container i am actually using.
2. Great, thank you! 😀

**Comment by danielquinn** [comment] 2017-11-01 11:31
I've just merged @pitkley's PR, so I'm going to close this assuming that all is well.  If that's not the case, feel free to re-open it.

**Closed by danielquinn** 2017-11-01 11:31 UTC

**Comment by pitkley** [comment] 2017-11-01 12:42
Thanks @danielquinn. I have rebuild the Docker Hub image, so it should now include the new `docker-entrpoint.sh` script. @dev-rke can you confirm if this fixes your permission issue?

**Comment by dev-rke** [comment] 2017-11-01 17:35
Hi @pitkley, hi @danielquinn,

thank you, i just tried it out:

I deleted the docker image pitkley/paperless.
Then i ran 
```$ docker-compose up -d```
and it threw the following error after pulling the new images:
```
Creating paperless_webserver_1
Creating paperless_consumer_1

ERROR: for webserver  Cannot create container for service webserver: Error processing tar file(exit status 1): mkdir /documents: file exists
ERROR: Encountered errors while bringing up the project.
```

When i run 
```$ docker-compose config```
i get the volumes listed for the consumer:
```
volumes:
    - data:/usr/src/paperless/data:rw
    - media:/usr/src/paperless/media:rw
    - /path/to/arbitrary/place:/consume:rw
```
Why is there /consume mounted against a default value in docker-compose.yml?
This does not make any sense. It should NOT mount a NONEXISTING path of my host system. 
The path "/path/to/arbitrary/place" was created on my host system automatically, because it is referenced in docker-compose.yml as volume. 
I was wondering, why there were still files left after i created the new container, even when i deleted the data volumes.
My recommendation: define some data volume for the /consume folder or create the folder only inside of the container. Creating unexpected folders on the host system is a very bad solution, nobody expects the files there.
When you do not wan't to create another data volume for /consume an even better alternative would be to use a relative folder as path, e.g. "./consume:/consume", so people won't wonder what is happening.

Therefore i removed the /consume volume from docker-compose.yml, but the consumer container still dies.
```
Parsers available: RasterisedDocumentParser
Consuming /consume/Lorem_Ipsum_Helvetica.png
Processing sheet #1: /tmp/paperless/paperless2735pb_0/convert-0000.pnm -> /tmp/paperless/paperless2735pb_0/convert-0000.unpaper.pnm
OCRing the document
Parsing for eng
Parsing for por
OCR for pt failed, but we're going to stick with what we've got since FORGIVING_OCR is enabled.
Completed
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 57, in handle
    self.loop()
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 67, in loop
    self.file_consumer.consume()
  File "/usr/src/paperless/src/documents/consumer.py", line 139, in consume
    self._cleanup_doc(doc)
  File "/usr/src/paperless/src/documents/consumer.py", line 223, in _cleanup_doc
    os.unlink(doc)
PermissionError: [Errno 13] Permission denied: '/consume/Lorem_Ipsum_Helvetica.png'
```

The issue with the folder permissions for the /consume directory is not solved.
Directory permissions:
```
# cd /consume
# ls -lah
total 140K
drwxr-xr-x  2 root      paperless 4.0K Nov  1 17:27 .
drwxr-xr-x 70 root      root      4.0K Nov  1 17:25 ..
-rw-rw-r--  1 paperless paperless  70K Oct 30 14:53 Lorem_Ipsum_Helvetica.png
```

The issue with the /export volume is solved, the directory is created. :-) 
```
# cd /export
# ls -lah
total 8.0K
drwxr-xr-x  2 root paperless 4.0K Nov  1 17:25 .
drwxr-xr-x 70 root root      4.0K Nov  1 17:25 ..
```
I currently don't know what the export folder is good for, but i think it should also have 775 permissions, because export implies there should be some data written into that folder? ;-)
Does it make sense to also mount that folder into a data volume?

**Comment by pitkley** [comment] 2017-11-01 17:59
> My recommendation: define some data volume for the /consume folder or create the folder only inside of the container. Creating unexpected folders on the host system is a very bad solution, nobody expects the files there.

The reason that the folder structure is created is because Docker will create a specified path rather than throwing an error.

The reason that `/consume` is not defined as a data volume is because we expect the main use-case to be that the end-user will not want to start copying files into the container but rather into a folder on the host. But I agree with you that `./consume:/consume` might be a better default.

> The issue with the folder permissions for the /consume directory is not solved.

I had forgot to update the referenced commit in the `Dockerfile` which gets build on Docker Hub. Can you please re-pull and verify that the issue is gone? I have tested it and verified that the permissions get set correctly now on my end.

**Comment by dev-rke** [comment] 2017-11-02 11:02
Ok, cool.
I will test it later. :-)

**Comment by dev-rke** [comment] 2017-11-04 15:00
Hi @pitkley,

it works as expected! :-)
Thanks for your support!

@danielquinn: i created a pull request upon our discussion regarding the ./consume:/consume flag in docker-compose.yml, please take a look at https://github.com/danielquinn/paperless/pull/269
