### ISSUE TITLE
Consumer Error and deleted Documents

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#131] opened 2016-07-06 17:28 UTC
I have to issues/questions:

1) During the consumption of my pdf files I always get the following error msg:
[image2 @ 0x8baff00] Encoder did not produce proper pts, making some up.
What did I wrong?

2) after the deletion of documents in the django UI the documents are still listed in the folders:
paperless/media/documents/originals
paperless/media/documents/thumbnails
Is it a Bug?

**Comment by danielquinn** [comment] 2016-07-09 15:20
1. Isn't an error so much as a warning and I get it too.  I don't think it's anything to worry about as it doesn't appear to have a negative effect on the output.
2. Yeah this is an ~~interesting~~annoying quirk of how Django handles local files, but yes I'd consider it a bug... a reasonably simply solved bug at that.  Basically, we have to override `.save()` to delete the file afterward and I think that's it.  I'll mark this ticket as a bug and will get to it when I can unless you'd like to offer a PR to fix this?

**Comment by Ulli2k** [comment] 2016-07-10 07:35
1. I thought so too but if I do a simple unpapier on the shell I do get an output file but it can not be opened, it is corrupted...I guess paperless just skips the unpapier optimization?

2. sorry I do not have any experience with python. it is very unhappy to block harddrive space...

**Comment by danielquinn** [comment] 2016-07-10 13:47
1. Nope, [it's there](https://github.com/danielquinn/paperless/blob/master/src/documents/consumer.py#L174)
2. Well it *is* just a document, so it's not like it's a lot of disk space, but I agree, this needs to be patched.

**Comment by avichalp** [comment] 2016-08-08 19:11
@danielquinn I think instead of overriding the save method of document model shouldn't we use a post-save signal and write a handler that deletes the document from the file system. I think it is more elegant than overriding a method of parent class. Also I guess it is not considered a good practice in the community to override a django methods such as save unless the person knows what he is really doing .

What do you suggest ?

**Comment by danielquinn** [comment] 2016-08-08 19:16
@avichalp you're probably right, but I'm lazy so overriding .save() is my go-to for something this simple.  I don't think there's anything inherently wrong with overriding public methods, so long as you do so responsibly:

```python
def save(self, *args, **kwargs):
    # do stuff
    models.Model.save(self, *args, **kwargs)
```

Even if the Django devs do something to change the nature of save, nothing bad can happen here.

With that said though, you're right: the more elegant solution is to wire up some signals.  If you were to submit a PR to do just that, I'd be happy to accept it :-)

**Comment by avichalp** [comment] 2016-08-10 06:58
@danielquinn I will try to submit a PR.

**Comment by Ulli2k** [comment] 2016-08-17 14:23
I just did an update via "git pull" and "python3 -m pip install  --user --requirement /opt/paperless/requirements.txt".
after running the python command I got the files which can be deleted. 
--> so far so good!

Some remarks/questions:
* also the files in the thumbnails folder have to be deleted manually
* After the manually deletion of the files the command still lists the same files which can be deleted!
* As far as I understand paperless will delete all in django deleted documents automatically from the folders originals and thumbnails from now, am I right?

**Comment by danielquinn** [comment] 2016-08-17 14:27
* I forgot about the thumbnails.  Oops.  I'll have to reopen this and fix that.
* The list still being there post-delete is really weird.  I'll try to reproduce it.
* Currently, only the original files will be deleted.  I forgot to also tell it about the thumbnails, so I'm going to re-open and do that too.  It might have to wait another week though, since most of my available time is on the weekend.

**Comment by danielquinn** [comment] 2016-08-20 13:12
Alright I've just pushed a fix to account for thumbnail deletion as well, so that should fixed for you as soon as you do a `git pull` (don't forget to migrate as well if you haven't already).

The new command to run to find files to delete is:

```python
for i in (set(range(1, Document.objects.order_by("-pk").values_list("pk", flat=True)[0])) - set(Document.objects.values_list("pk", flat=True))):
     print(Document(id=i, file_type="*").source_path)
     print(Document(id=i, file_type="*").thumbnail_path)
```

Note however that this will just give you the "gaps" in the database, and doesn't do any actual checking for the existence of files on your disk.  Therefore, @Ulli2k's note that after file deletion the list still shows the same is totally expected.

I think this is good now, so I'm closing this ticket.  If someone finds a bug though, feel free to re-open.

**Closed** 2016-08-20 13:15 UTC
Labels: bug
