### ISSUE TITLE
Issue with MySQL/MariaDB as backend

### ISSUE THREAD

**Issue by EntRhoPi** [danielquinn/paperless#183] opened 2017-01-15 14:49 UTC
When choosing MySQL as Backend the initial db creation runs into an error like this:
```BLOB/TEXT column 'content' used in key specification without a key length```

This is because (from my understanding) the index size limit for InnoDB tables is 767 bytes and since the field "content" is to be indexed but of type "LONGTEXT" it shows the error above running ```./manage.py migrate```

To fix this line 22 of ```src/documents/migrations/0001_initial.py``` should be:
```('content', models.TextField(db_index=False)),```

I'm not sure how PostgreSQL handels this.

**Comment by danielquinn** [comment] 2017-01-15 16:48
PostgreSQL indexes these types of columns (one of the reasons I prefer it over MySQL).  The thing is, *the whole purpose* of Paperless is to make the content in the documents searchable, so removing the index so MySQL is happy isn't really something I want to do.

Additionally, it's kinda odd that Django doesn't handle this for us.  It is after all a database-generic ORM, so it should manage this situation accordingly.

What version of MariaDB are you running?  Perhaps it's a version thing and not something Django is handling.

**Comment by EntRhoPi** [comment] 2017-01-15 18:43
Would be nice to use it with any DB type but if it's too much of a hassle I might as well switch to PostgreSQL.

I'm currently using the Version 10.0.28 (which is shipped with Ubuntu 16.04).
I'll try the other versions available (namely 10.1.x and 10.2.x) and report back.

Interestingly enough the search function still works with that one. I guess at least that's what Django is handling right. I don't have that many docs in my database to say something about performance thou.

**Comment by EntRhoPi** [comment] 2017-01-16 20:42
So, I've been fiddeling around with the different versions but it seems to be the same issue with all of them.

As I said before, the search functionality works even with MySQL but I can't foresee the performance hit one might have with a couple hundred or thousand documents.

Maybe there could be another column in the future that consists of the documents content but without stop words so the index size might be just within those limitations.

**Comment by danielquinn** [comment] 2017-01-17 16:20
Yeah I see your point about the index.  You don't exactly *need* one if you're not dealing with that many documents, so I can see why you haven't noticed any performance problems so far.

The bitch of it is, I don't think it's safe for me to remove the index now as doing so would create a migration to remove it and if I edit the initial migration file to remove the index then the current version of Paperless will always be out of sync with user's individual installations.  Ick.

I'm going to have to do some experimentation on this myself to see if I can find a work around, and maybe talk to the Django folks about this if indeed it is a bug in how Django handles index declarations wrt MySQL.  Until then, I'm going to leave this open so other MySQL users can find it should they run into trouble.

**Comment by danielquinn** [comment] 2017-01-22 18:45
I just had a thought.  By default, Paperless has the database driver set to use PostgreSQL's `psycopg2` if you set `PAPERELSS_DB_USER` etc.  If you haven't changed these values to use the appropriate MySQL driver, weird stuff may be happening.

**Comment by EntRhoPi** [comment] 2017-01-23 09:28
I've set up the connection according to https://docs.djangoproject.com/en/1.9/ref/settings/#databases as referenced in the ```settings.py``` using the mysql driver.

2 things I observed (which should probably go into a different issue, or this one should be renamed):

1.
setting up```PAPERLESS_DBUSER``` and ```PAPERLESS_DBPASS``` in ```/etc/paperless.conf``` which should switch to the PostgreSQL or in my case MySQL Database only works for the webinterface, if set up the cunsumer still uses the SQLite DB. I had to replace the SQLite connection entirely in the ```settings.py``` to make it work.

2.
I tried PostgreSQL. But it stops while migrating (initializing) on file ```0003_sender.py``` like so:
  ```
Running migrations:
  Applying documents.0003_sender...Traceback (most recent call last):
  File "/home/paperless/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: operator class "varchar_pattern_ops" does not accept data type integer
```
The problem lies here:
```
migrations.AlterField(
    model_name='document',
    name='sender',
    field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Sender'),
),
```
Not sure thou what exactly the problem might be. My Django knowledge is basically nonexistent.

**Comment by danielquinn** [comment] 2017-01-24 19:29
I've got a lengthy train trip this weekend, so I'll try to revisit this then and see what I can make of it.

**Comment by danielquinn** [comment] 2017-02-18 18:01
I'm sorry for the delay on this, but I've found some time to look into this today.

First, some confirmations:

* I was able to reproduce both the problems you had with MySQL and PostgreSQL.  It would appear that I had too much faith in Django's cross-database support when it comes to migrations.
* The MySQL problem is only in [one place](https://github.com/danielquinn/paperless/blob/master/src/documents/migrations/0001_initial.py#L22) thanks to [how miserably MySQL supports indexes](http://stackoverflow.com/a/1827099/231670).  The fix is, as you suggest, simply removing `db_index=True` from that line and everything Just Works after that.
* The PostgreSQL problem was annoying: basically I changed the `sender` field from a `CharField` to a foreign key and Django inturpretted this to do an `AlterField` migration -- which works just fine in SQLite (which is why I didn't see it) but blows up in Postgres.  

Now some good news: I've fixed both:

* The MySQL problem was averted by adding a test in the migration.  If `mysql` is in your database `ENGINE` definition (as it would have to be for Paperless to work with MySQL) then the migration will now simply disable indexes on that column at creation time.  Unfortunately, this means that any future development will have to take this hack into account when tinkering with the index that may-or-may-not exist on that column, but I'm not worrying at this point.
* The PostgreSQL problem was fixed by manually breaking the `AlterField` step into two separate ones: `RemoveField` and `AddField`.  Users who already have a working system won't have to change anything, and new users will have a working migration now.

Regarding the config not working for the consumer but working for the web, I can't reproduce that, and honestly, that would be *really* weird as the database connection is only configured in one place.  What *is* likely however is that while you were experimenting with different databases, you changed the configuration and didn't restart both services.  Remember that Django will continue using whatever configuration you've given it until you restart the service in question, so if you change the config and restart only the webserver, the consumer will continue using the old setup until you restart that too.

Anyway, I've merged those changes into master and you should see them with a `git pull`.  Give it a try and let me know if things work out.  Until then, I'll close this issue and maybe I'll have a talk with some of the Django folks about this.  At the very least, this feels like something that could be documented better.

**Closed by danielquinn** 2017-02-18 18:01 UTC

**Comment by EntRhoPi** [comment] 2017-03-05 10:56
Yeah, no problem, I was quite busy too.

So ... I did some extensive testing with alle the DB types this weekend and everything seems to be working fine now.

As for the consumer it was as you've guessed. I did forget to restart it.

Thanks a bunch and keep up the great work!

**Comment by danielquinn** [comment] 2017-03-05 11:50
Quick update: this issue has since spawned two separate issues in the Django bug tracker and both have been accepted by the dev team: [#27859](https://code.djangoproject.com/ticket/27859) and [#27860](https://code.djangoproject.com/ticket/27860).  So in our own little way, this project and your reporting have helped make Django better :-)
