### ISSUE TITLE
Document_consumer django.db.utils.IntegrityError

### ISSUE THREAD

**Issue by manderso7** [danielquinn/paperless#107] opened 2016-04-08 18:28 UTC
I've got this installed on a Raspberry Pi 3, and its starting out ok for me, except for the error I just received. I'm trying to add a couple of my bills to test the consumer. The first try was without an edited filename, so date_autopay.pdf, which gave it nothing to go on, so no correspondent obviously. I then added another document to the consumer directory, naming it YYYYMMDD - Correspondent - autopayment - bill.pdf. After a while of it "parsing for eng" I got a lenthy stack trace:  
`Parsing for eng
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: documents_document.checksum

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/opt/paperless-master/src/documents/management/commands/document_consumer.py", line 55, in handle
    self.loop()
  File "/opt/paperless-master/src/documents/management/commands/document_consumer.py", line 65, in loop
    self.file_consumer.consume()
  File "/opt/paperless-master/src/documents/consumer.py", line 129, in consume
    document = self._store(self._get_ocr(imgs), doc, thumbnail)
  File "/opt/paperless-master/src/documents/consumer.py", line 303, in _store
    datetime.datetime.fromtimestamp(stats.st_mtime))
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: documents_document.checksum
`

Can you think of how I can get around this?

**Comment by JaimeObregon** [comment] 2016-04-08 18:37
Are you re-importing an already indexed document? If so, please see #105 and #104.

**Comment by danielquinn** [comment] 2016-04-08 18:38
This is very strange because it looks like there are a few problems here:

1. You're getting an integrity error on the checksum, which tells me that Paperlesshas compared the document you're importing to those it already has in the database and it thinks that this new one is a duplicate.  Is that likely?
2. It's *not* however failing gracefully. Rather, it's actually failing at the database insert stage instead of doing a check and during the initial stages of the consumption.

If I had to guess, I'd say that you updated Paperless, but didn't stop and restart the consumer.  Am I right?

**Comment by manderso7** [comment] 2016-04-09 01:40
It's a similar document, but not the same. Could be that the only differences in them are the dates and perhaps one or two other fields.

This is a brand new install, and it's worked once. Afterwards, when it happens, the consumer crashes. Re-running the consumer results in the same problem.

I've also tried it on a completely different document (first was cable company, second was cable company from a different month, third was a credit card), with the same error.

**Comment by danielquinn** [comment] 2016-04-09 19:25
The first time I wrote a response for this, my browser exploded and ate the whole thing, so I'll try to recreate it all from memory.

What we're going to have to do is rule out  some things, and then attempt a diagnosis with other bits of information as well.  Just follow these instructions and we'll see what we can make of it all.

1. Stop the consumer and do a `git pull` to make sure that everything is up to date.  Finally, run `./manage.py migrate` to make sure that your database is up to date as well.
2. Now that we can be sure that the code is up to date, open up `src/documents/consumer.py` and make sure that [this line](https://github.com/danielquinn/paperless/blob/master/src/documents/consumer.py#L105) is in there.  So long as you've got a recent git instance, it should be ok, but I just want to be sure.
3. Run the following command in the `src` directory to get a snapshot of the documents currently in your database:

        echo "SELECT id, checksum, title FROM documents_document;" | ./manage.py dbshell

    Post the output of this command here so we can keep up on what's going on.
4. Now we're going to compare the two files that are conflicting.  If I understand your situation correctly, you only have one file currently indexed with Paperless, so use the UI to download it to `/tmp` and name it `file1.pdf`.  Next, find the file that's causing this error and copy it to `/tmp` and name it `file2.pdf`.  When that's complete, run the following command:

        md5sum /tmp/file1.pdf /tmp/file2.pdf

Post the output of that command here too, and we'll see what can be done from there.

**Comment by manderso7** [comment] 2016-04-09 21:08
When I originally downloaded Paperless, I pulled down this zip file. Figured that's not exactly future proof, so I cloned on top of the directory, and of course overwrote the file that was in the Db. Well ok, then I'll just scan it in again. Nope. Same error. I've also tried a completely different file, also same error. So, nothing's in the snapshot of the db.  
I've run the migrate command after the clone (still using my /etc/paperless.conf file). 

So, if you're keeping score, I don't have anything in the database, so I don't have anything to do an md5 to. I'm at the point of thinking that my dependencies aren't installed correctly.  Your thoughts?

BTW, thanks for replying and trying to help. It's appreciated.

**Comment by danielquinn** [comment] 2016-04-10 12:17
It sounds like your installation is totally hosed somewhere, as I can't think of any case where you could get a UNIQUE constraint failure when you don't actually have any records in the database.  Given the unfortunate way you did the installation, and the fact that there doesn't appear to be anything in the database at present, I'd recommend that you wipe & start again and see if you can reproduce the error:

```bash
rm -rf /path/to/paperless /etc/paperless.conf
cd /path/to
git clone https://github.com/danielquinn/paperless.git
cd paperless
cp paperless.conf.example /etc/paperless.conf
${EDITOR} /etc/paperless.conf
cd src
./manage.py migrate
./manage.py createsuperuser
```

The [documentation](http://paperless.readthedocs.org/en/latest/setup.html) will give you a much more thorough run-down of how to do this of course.

Once it's working, start the consumer and put your files in your consumption dir and see how that pans out.  My guess is that provided you actually deleted everything first, this error should go away for you.

**Comment by manderso7** [comment] 2016-04-11 01:07
I've done as you asked, and checked my versions of installed software. Pillow was lower than required, so I've updated that. All other packages are up to date.
It's imported the first document correctly, though it didn't like my naming scheme, i'll have to work on that. I'll update tomorrow to let you know if it imported rest of the documents. This is an rpi3, so will take a bit.

**Comment by manderso7** [comment] 2016-04-11 11:31
Ok, same error, but now I can run those troubleshooting commands:  
`pi@kpi:/opt/paperless/src $ sudo echo "SELECT id, checksum, title FROM documents_document;" | ./manage.py dbshell
1||20160123-Charter-Bill`  
`
pi@kpi:/tmp $ mv 20160411004920-20160123-charter-bill.pdf file1.pdf
pi@kpi:/tmp $ mv 20160314-Suntrustcc-Statement.pdf file2.pdf
pi@kpi:/tmp $ md5sum file1.pdf file2.pdf
415f1c547c141f0ebedf978c0f319da2  file1.pdf
ec8bfb5157bad7d54462d000501dbfba  file2.pdf`  

Again, thanks for your help.

**Comment by darb** [comment] 2016-04-11 12:19
I'm having the same issue on a fresh install
[error.txt](https://github.com/danielquinn/paperless/files/212894/error.txt)
I get this error after the first import of a file is successful, but any subsequent file errors out.

**Comment by evils** [comment] 2016-04-11 15:37
I have the exact same problem as @manderso7 has. Same error message on a slightly different document

**Comment by danielquinn** [comment] 2016-04-11 15:39
Lovely.  Well something's definitely amiss.  I'll spend a couple hours later this week then, trying to reproduce it locally.  I'll post back here when I have something.

Those of you who know your way around Python: feel free to try to debug this one yourselves and issue a PR or just some code snippets in the mean time.  My week is pretty full up 'till Wednesday though, so this may take a while.

**Comment by evils** [comment] 2016-04-11 15:41
I'm trying my best, but I'm not a python pro.

If you want to debug it on my rpi, I can give you ssh access.

**Comment by evils** [comment] 2016-04-11 17:58
Thanks to my slow internet connection I spend two hours trying to debug this, but I think I got a little closer now ...
The problem what seems to be happening is that the consumer isn't creating a checksum for newer documents.
I consumed one tiff that ended up in the database without a checksum, see:

`19|941ee94d840af5e7b41025f45d315e9a|1458756611230316
20|5842fcb521ab8abf0c15032acf278aca|1458758312230316
21|9070c1b027a361338e28a6bde120862a|292928191033455
22|ea6d89e53bd487a8a9caa7899ea8e871|1459347249300316
24||20160330145803-zahnarzt`

When trying to consume the next document then, I get the crash due to the broken constraint. 

I need to get back to my normal programming work for today, but will look further into this soon.

**Comment by danielquinn** [comment] 2016-04-11 22:31
Thanks @evils, this really helped me figure out what was going wrong.  I dug into the code and sure enough, the `.create()` step was creating a document with a checksum of `''`.  Interestingly, even though the field in Django has `blank=False`, this was still permitted by Django's model layer and I'm still not sure why, but I've since fixed it and it appears to be working.

You all should update with `git pull` and then restart the document consumer.  That should fix this problem.

Thanks to all of you for finding this and especially to @manderso7 for sticking through all of my dumb questions to figure out what was wrong.  I'm going to close this issue now, but feel free to re-open if you think this is still happening.

**Closed by danielquinn** 2016-04-11 22:31 UTC
