### ISSUE TITLE
Find the first date in the OCRed text

### ISSUE THREAD

**Issue by zorglups** [danielquinn/paperless#158] opened 2016-10-04 21:30 UTC
Hello,

I'm really glad I found your project because I was thinking of doing it but was procrastinating it as much as my paper sorting ;-)

Many thanks for sharing your work!!!

I have a paper scanner with a feeder (that can even do 2 sides scan). It writes pages as JPG (300dpi) onto a samba share (or an FTP server).

A custom script does:
- "convert wizard.jpg -quality 0 wizard.jp2" because jpg produced by the scanner are too big.
- recognize multipages documents and groups pages from the scanner into one single pdf using [img2pdf](https://github.com/josch/img2pdf)

I then planned to use [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF) to create nice PDF/A compliant files.

The output of OCRmyPDF will then enter paperless and get tagged automatically.

One of the most important metadata of the document is its (printed) date.

Could you enhance paperless to be able to find the first date found in the ORCed text and use it by default as document date?
Here is a concrete example of how to achieve it in Python: [http://stackoverflow.com/questions/6562148/python-finding-date-in-a-string](http://stackoverflow.com/questions/6562148/python-finding-date-in-a-string)

Best regards,

Pierre

**Comment by danielquinn** [comment] 2016-10-05 09:22
That sounds like a pretty handy feature, and I think something like it has been requested before.  Unfortunately, I just don't have the time to write something like that as I've got my hands full with another side project these days.

However, if you were to write a pull-request with this, I'd be happy to merge it.  It would involve introducing a hook [here](https://github.com/danielquinn/paperless/blob/master/src/documents/consumer.py#L296) that takes the `text` variable and determines `created` if it hasn't already been sourced from the file name via `FileInfo.from_path()`.

Note that one of the requirements for Paperless is [dateutil](https://pypi.python.org/pypi/python-dateutil) so you can use that to parse dates.  I'd rather not add another requirement if we don't have to.

**Comment by zorglups** [comment] 2016-10-06 06:51
Ok. I'll let you know when it is done. Thank you for pointing to the right way to insert it.
Honestly, I'm busy with 100 side projects and it may be a while before it comes... but it will come ;-)

Just a question (as I did not use/read paperless code yet).

What does paperless do with PDF which are already OCRed? Does it redo the OCR job or does it skip it?

**Comment by danielquinn** [comment] 2016-10-06 08:43
Heh.  You just stumbled onto one of the really annoying shortcomings of this project.  Currently, *all* PDFs are rasterised as images and OCR'd, regardless of whether they're paper scans or generated with text already in the file somewhere.

The problem is that *I don't know how to get the text out* so I haven't included that feature.  Additionally, even if I knew how to get it out, I'd have to short-circuit the process of OCRing the document whilst still generating the thumbnail.  None of this is insurmountable of course, it just takes time that I don't have right now :-(

So, if you'd like to issue as separate PR with support for PDFs with a text subchannel, that would be awesome too :-)

**Comment by danielquinn** [comment] 2018-01-29 11:05
**Update**: @BastianPoe has issued a PR for this #291.  We're trying to see if we can do away with one of the required libraries, but outside of that the PR is excellent and will likely make its way into the codebase soon.

**Comment by danielquinn** [comment] 2018-02-03 13:15
The aforementioned PR is now merged!  Closing this now.

**Closed by danielquinn** 2018-02-03 13:15 UTC
Labels: I won't do it but contributions welcome, enhancement
